config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  get '/', to: 'welcome#index'

  shallow do
    resources :users do
      resources :workouts do
        resources :exercises do
          resources :exercise_histories
        end
      end
    end
  end

get '/timer' => 'timers#show'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :name, presence: true
  validates :name, inclusion: { in: ["squats", "bench press", "deadlift", "pullups", "pushups", "rows", "curls", "squat thrusts", "skull crushers", "lunges"], message: "%{value} is not a valid type"}

   belongs_to :workout
   has_many   :exercise_histories

end

app/models/exercise_history.rb
class ExerciseHistory < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise

  def self.total_sets(user_id, exercise_id)
    total = 0
    user = User.find(user_id)
    histories = user.exercise_histories.where(exercise_id: 1)
    histories.each {|exc| total += exc.sets.to_i}
    return total
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
  has_many :exercises, through: :workouts
  has_many :exercise_histories, through: :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
  has_many   :exercises
  has_many :exercise_histories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_filter{ response.content_type = 'application/xhtml+xml' }
  def after_sign_in_path_for(resource)

    request.env['omniauth.origin'] || stored_location_for(resource) || user_workouts_path(current_user)
  end
end

app/controllers/exercise_histories_controller.rb
require 'json'

class ExerciseHistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exercise_histories = ExerciseHistory.all
  end

  def new
    @exercise_history = ExerciseHistory.new
    @exercise = Exercise.find(params[:exercise_id])
  end

  def show
    @exercise_history = ExerciseHistory.find(params[:id])
    @exercise_name = @exercise_history.exercise.name
    if @exercise_name == "squats"
      @history1 = {thighs: 20, glutes: 15, abs: 10, biceps: 0, chest: 0}
      @history2  = {thighs: 20, glutes: 15, abs: 10}
    elsif @exercise_name == "bench press"
      @history1 = { chest: 20,  biceps: 10, abs: 5}
      @history2  = { chest: 20,  biceps: 10, abs: 5}
    elsif @exercise_name == "deadlift"
      @history1 = {thighs: 5, back: 10,  biceps: 12, glutes: 8, abs: 15}
      @history2  = {thighs: 7, back: 8,  biceps: 15, glutes: 5, abs: 10}
    elsif @exercise_name == "pullups"
      @history1 = {chest: 10,  biceps: 15, glutes: 5, abs: 15}
      @history2 = {chest: 12,  biceps: 15, glutes: 5, abs:  15}
    elsif @exercise_name == "pushups"
      @history1 = {thighs: 3, chest: 18,  biceps: 10, glutes: 5, abs: 12}
      @history2  = {thighs: 3, chest: 18,  biceps: 10, glutes: 5, abs: 12}
    elsif @exercise_name == "rows"
      @history1 = {thighs: 15, chest: 5,  biceps: 4, glutes: 10, abs: 8}
      @history2  = {thighs: 15, chest: 5,  biceps: 4, glutes: 10, abs: 8}
    elsif @exercise_name == "curls"
      @history1 = {chest: 5,  biceps: 20}
      @history2  = {chest: 5,  biceps: 20}
    elsif @exercise_name == "squat thrusts"
      @history1 = {thighs: 13, chest: 10,  biceps: 7, glutes: 15, abs: 15}
      @history2  = {thighs: 13, chest: 10,  biceps: 7, glutes: 15, abs: 15}
    elsif @exercise_name == "skull crushers"
      @history1 = {chest: 5,  biceps: 10, abs: 5}
      @history2  = {chest: 5,  biceps: 10, abs: 5}
    elsif @exercise_name == "lunges"
      @history1 = {thighs: 15, biceps: 12, glutes: 20, abs: 5}
      @history2  = {thighs: 15, biceps: 15, glutes: 20, abs: 5}
    end

  end

  def create
    exercise = Exercise.find(params[:exercise_id])
    @exercise_history = exercise.exercise_histories.build(exercise_history_params)
    if @exercise_history.save
      redirect_to exercise_history_path(@exercise_history.id)
    else
      redirect_to user_workouts_path(current_user)
    end
  end

  def update
    @exercise_history = ExerciseHistory.find(params[:id])

    if @exercise_history.update(params[:exercise_history_params])
      redirect_to exercise_history_path
    else
      flash[:error]= "could not locate that workout history"
      redirect_to edit_exercise_history_path
    end
  end

  private

  def exercise_history_params
    params.require(:exercise_history).permit(:weight, :sets, :reps, :rest, :distance, :running_time)
  end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
    @workout = Workout.find(params[:workout_id])
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def create
    workout = Workout.find(params[:workout_id])
    @exercise = workout.exercises.build(exercise_params)
    if @exercise.save
      redirect_to workout_path(workout.id)
    else
      render json: "failed".to_json
    end
  end

  def update
    @exercise = Exercise.find(params[:id])

    if @exercise.update(params[:exercise_params])
      redirect_to exercise_path
    else
      flash[:error]= "could not locate that exercise history"
      redirect_to edit_exercise_path
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    redirect_to exercise_path
  end

  private

  def exercise_params
    params.require(:exercise).permit(:workout_type, :sets, :name, :weight, :reps, :rest, :tempo, :distance, :running_time, :user_id, :workout_id)
  end

end

app/controllers/timers_controller.rb
class TimersController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :layout => "welcome"
  end

end

app/controllers/workout_controlller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:workout_id])
  end

  def create
    @workout = Workout.new(params[:workout])
    if @workout.save!
      redirect_to workout_path
    else
      flash[:error]= "could not locate that workout history"
      redirect_to new_workout_history_path
    end
  end

  def update
    @workout = Workout.find(params[:id])

    if @workout.update(params[:workout_params])
      redirect_to exercise_path
    else
      flash[:error]= "could not locate that workout history"
      redirect_to edit_workout_path
    end
  end

  private

  def workout_params
    params.require[:workout].permit(:name, :user_id)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # before_action :authenticate_user!


  def index
    @workouts = Workout.all
    @workout = Workout.new
  end

  def new
    @workout = Workout.new
  end

  def show
    @workouts = Workout.where(params[:user_id])
    @workout = Workout.find(params[:id])
    @exercises = Exercise.where(workout_id: @workout.id)
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save!
      redirect_to new_workout_exercise_path(@workout.id)
    else
      flash[:error]= "could not locate that workout history"
      redirect_to new_workout_history_path
    end
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])

    if @workout.update(workout_params)
      redirect_to user_workouts_path(params[:id])
    else
      flash[:error]= "could not locate that workout history"
      redirect_to edit_workout_path
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to user_workout_path(params[:id])
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def inline_svg(path)
	    File.open("app/assets/images/#{path}") do |file|
	    raw file.read
	  end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exercise_histories/index.html.erb
<div class="svg-container">
</div>

<div id="num_sets" style="display:none">

  <% if @exercise_history %>
  <%= @exercise_history.sets %>
  <% end %>
 </div>
   <!-- <%= image_tag 'abs.svg', :id => "abs"%> -->
</div>

<div class="exercise_performance">
EXERCISE HISTORY

<% current_user.exercises.each do |exercise| %>
  <%= exercise.name %>
  <% exercise.exercise_histories.each do |p| %>
    ADD DATE OF EXERCISE USING DATE/TIME THING
    <%= p.name %><br/>
    <%= p.sets %><br/>
    <%= p.reps %><br/>
    <%= p.weight %><br/>
    <%= p.tempo %><br/>
  <% end %>
<% end %>
</div>

app/views/exercise_histories/new.html.erb
<div class="background5">
</div>

<div class="goals">
  <h3><strong>GOALS FOR <%= @exercise.name.upcase %></strong></h3> <br/>
  <h3>SETS: <span class="set-amount" data-sets=<%=@exercise.sets%>><%= @exercise.sets %> </span></h3>
  <h3>REPS: <%= @exercise.reps %></h3>
  <h3>WEIGHT: <%= @exercise.weight %></h3>
  <h3>TEMPO: <%= @exercise.tempo %></h3>
  <h3>REST:<span class="rest_time" data-rest=<%= @exercise.rest %>> <%= @exercise.rest %> </span></h3>
</div>
<div class="set_show"><h1 >Set: <span class="set_num"></span></h1></div>
<div class="done-ex-input">
<h3>Achieved</h3>
<%= form_for @exercise_history, url: {action: "create"} do |f| %>
  Sets :<%= f.text_field :sets, :placeholder => @exercise.sets %> <br/>
  Reps :  <%= f.text_field :reps, :placeholder =>  @exercise.reps %> <br/>
  Weight: <%= f.text_field :weight, :placeholder => @exercise.weight %> <br/>
  Tempo: <%= f.text_field :tempo, :placeholder => @exercise.tempo %> <br/>
  <%= hidden_field(:exercise_history, :rest) %>
  <%= f.submit "Create" %>
<% end %>

<h4 class="average"><strong>Your Actual Rest Time was an average of <span class="final_show"></span> seconds per set.</strong></h4>

</div>

<input type="checkbox" id="toggler" class="modal-toggler">

<section class="exercise-container">
  <label for="toggler" class="modal  close-modal-area"></label>
  <div class="modal  modal-box">
    <h2> <span class="minutes" style="color:white" ></span>0<span class="minute" style="color:white">0</span><span class="colon" style="color:white">:</span><span class="seconds" style="color:white">0</span><span class="second" style="color:white">0</span></h2>
    <label for="toggler" class="workout toggle-modal-button"><h1 style="color:white">Workout!</h1></label>
  </div>
</section>
<section class="content">
  <div class="modal">
    <div class="work_holder">
      <div class="toggle-modal-button"><h1 style="color:white">Begin Workout!</h1>
      </div>
    </div>
    <div class="timer_holder"><label for="toggler" class="toggle-modal-button timer_button"><span><h1 style="color:white">Rest!</h1></span></label>
    </div>
<!-- <div class="exit_holder"><div class="toggle-modal-button">Quit!</div></div> -->
    <p></p>
  </div>
</section>

app/views/exercise_histories/show.html.erb
<div class="history_tables">
  <div class="history">
    <table style="width:200px" id="muscle_table">
      <th>
        <caption class="values"><%= @exercise_name.upcase %></caption>
        <tr>
        <td class="values">Name</td>
        <td class="values">Sets</td>
        </tr>
      </th>
      <tbody id="muscle_table_body">
      <% @history1.each do |k,v|%>
        <tr id="mRow">
          <td id="mName" class="values"><%= k %></td>
          <td id="mvalue" class="values"><%= v %></td>
        </tr>
      <%end%>
       </tbody>
     </table>
     <button class="viewMuscles">chart</button>

      <table style="width:200px" id="muscle_table_2">
      <th>
        <caption class="values"><%= @exercise_name.upcase %></caption>
        <tr>
        <td class="values">Name</td>
        <td class="values">Sets</td>
        </tr>
      </th>
      <tbody id="muscle_table_body">
      <% @history2.each do |k,v|%>
        <tr id="mRow">
          <td id="mName" class="values"><%= k %></td>
          <td id="mvalue" class="values"><%= v %></td>
        </tr>
      <%end%>
       </tbody>
     </table>
     <button class="viewMuscles2">chart</button>
  </div>
</div>

<div id="body">
</div>

<div class="svg-container">
</div>

<div id="line-chart" style="min-width: 400px; max-width: 600px; height: 400px; margin-top: 0px; float: right;"></div>

app/views/exercises/index.html.erb
<%= render 'shared/search' %>
<div class="search_container">
<table class="search_table">
	<tbody>
<% @exercises.each do |exercise| %>
		<tr class="search_row" style="display: none"><td><%= exercise.name %></td></tr>
<% end %>
</tbody>
</table>
</div>

app/views/exercises/new.html.erb
<div class="background4">
</div>

<div class="wrapper">
<h1><u><%= @workout.name.upcase %></u></h1>
<h3><%= link_to "RETURN TO #{@workout.name.upcase} EXERCISES", workout_path(@workout.id) %></h3>
<h3><%= link_to "RETURN TO ALL WORKOUTS", user_workouts_path(current_user) %><br/><br/>

<%= form_for @exercise, url: {action: "create"} do |f| %>
  <%= f.select :name, [ ['SELECT AN EXERCISE'],['SQUATS', 'squats'], ['BENCH PRESS', 'bench press'], ['DEADLIFT', 'deadlift'], ['PULLUPS', 'pullups'], ['PUSHUPS', 'pushups'], ['ROWS', 'rows'], ['CURLS', 'curls'], ['SQUAT THRUSTS', 'squat thrusts'], ['SKULL CRUSHERS', 'skull crushers'], ['LUNGES', 'lunges']], :class => "exerciseFormInput", :require => true %><br/><br/>
  <%= f.text_field :sets, :class => "exerciseFormInput", :placeholder => "SETS"%><br/><br/>
	<%= f.text_field :reps, :class => "exerciseFormInput", :placeholder => "REPS" %><br/><br/>
	<%= f.text_field :weight,:class => "exerciseFormInput", :placeholder => "WEIGHT" %><br/><br/>
	<%= f.text_field :tempo, :class => "exerciseFormInput", :placeholder => "TEMPO" %><br/><br/>
	<%= f.text_field :rest, :class => "exerciseFormInput", :placeholder => "REST" %><br/><br/>
	<%= f.submit "Create" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>REST-LESS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav>
      <div id="logo">
        <a href="/">REST-LESS</a>
      </div>
      <div id="navBarButtons">
        <% if user_signed_in? %>
          <%= button_to('Logout', destroy_user_session_path, :method => :delete, :class=> "navButton") %>
        <% else %>
          <%= button_to('LOGIN', new_user_session_path, :method => "get", :class => "navButton")  %>
          <%= button_to('SIGN UP', new_user_registration_path, :method => "get", :class => "navButton") %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </div>
</body>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/highcharts-more.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>REST-LESS</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="background.css" rel="stylesheet">
</head>
 <body >
 	<div class="background">
     <%= yield %>
	</div>
</body>
</html>

app/views/shared/_navigation_bar.html.erb
<nav>
  <div id="logo">
    <a href="/">REST-LESS</a>
  </div>
  <div id="navBarButtons">
    <% if user_signed_in? %>
      <%= button_to('Logout', destroy_user_session_path, :method => :delete, :class=> "navButton") %>
    <% else %>
      <%= button_to('LOGIN', new_user_session_path, :method => "get", :class => "navButton")  %>
      <%= button_to('SIGN UP', new_user_registration_path, :method => "get", :class => "navButton") %>
    <% end %>
  </div>
</nav>

app/views/shared/_search.html.erb
<input type="text" class="search_input"><button class="search">Search</button>

app/views/timers/show.html.erb
<!--   <div class="rest_timer">
<div>
  <span class="minutes"></span>0<span class="minute">0</span><span class="colon">:</span><span class="seconds">0</span><span class="second">0</span>
</div>

  </div> -->
<input type="checkbox" id="toggler" class="modal-toggler">

<section class="exercise-container">
  <label for="toggler" class="modal  close-modal-area"></label>
  <div class="modal  modal-box">
    <h1>  <span class="minutes"></span>0<span class="minute">0</span><span class="colon">:</span><span class="seconds">0</span><span class="second">0</span></h1>
    <label for="toggler" class="toggle-modal-button">Workout!</label>
  </div>
</section>
<section class="content">
  <div class="modal">

  <input class="timer_input" type="number"><button class="timer_button">Time It!</button><label for="toggler" class="toggle-modal-button">Rest!</label>
<p>w</p>
  </div>
</section>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= @user.email %>

app/views/welcome/_signup.html.erb
<div class="background6">
</div>

<div class="signup">
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true %></div>

  <div><%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>

<%= render "users/shared/links" %>

</div>

app/views/welcome/index.html.erb
  <span >welcome</span>

<div class="welcomeIndex">
 <h2>WELCOME TO REST-LESS</h2>
  <div class="optionsBox">
    <% if user_signed_in? %>
      <ul>
        <h3 style="color: white">Do You Want to: </h3>
      <li id="links"><%= link_to "Create A New Workout", new_user_workout_path(current_user) %></li>
     <li id="links", ><%= link_to "View All Workouts", user_workouts_path(current_user) %><br/></li></li>
     </ul>
    <% else %>
      <h3 class="logInMessage"></h3>
    <div class="welcomeButtons">
      <%= link_to('Login', new_user_session_path, :method => "get", :class => "authenicate_button")  %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to('Sign Up', new_user_registration_path, :method => "get", :class => "authenicate_button") %>
    </div>
    <% end %>
  </div>
</div>

app/views/workouts/_new.html.erb
<%= form_for @workout, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/workouts/edit.html.erb
<%= form_for @workout, url: {action: "update"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Update" %>
<% end %>

app/views/workouts/index.html.erb
<div class="background3">
</div>
  <div class="workoutsIndex">
    <div class="left">
      <h1><u>YOUR WORKOUTS</u></h1>
      <%= form_for @workout, url: {action: "create"} do |f| %>
        <%= f.text_field :name, :placeholder => "Create New Workout" %>
        <%= f.submit "Create" %>
      <% end %>

      <% current_user.workouts.each do |workout| %>
        <table class="yourWorkouts">
          <th colspan="2"><span class="workoutTitle"><%= workout.name %></span></th>
          <tr>
            <td><%= link_to "WORKOUT NOW", workout_path(workout.id) %></td>
            <td><%= link_to "ADD EXERCISE", new_workout_exercise_path(workout.id) %></td>
          </tr>
       </table>
      <% end %>
    </div>
    <div class="center">
      <h1 class="centerHeader"><u>VIEW WORKOUT HISTORY</u></h1>
        <% current_user.workouts.each do |workout| %>
        <table class="workoutHistoryTable">
          <th colspan="3"><%= workout.name.upcase %><th/>
            <tr>
            <% workout.exercises.each do |exercise| %>
             <td> <%= link_to "#{exercise.name}", new_exercise_exercise_history_path(exercise.id)  %></td>
            <% end %>
          </tr>
        </table>
        <% end %>
    </div>
  </div>

app/views/workouts/new.html.erb
<%= form_for @workout, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/workouts/show.html.erb
<div class="background2">
</div>
<div class="workoutShow">
  <h1><u><%= @workout.name.upcase %></u></h1>
  <h3><%= link_to "RETURN TO YOUR WORKOUTS", user_workouts_path(current_user) %></h3>
  <h3><%= link_to "ADD AN EXERCISE", new_workout_exercise_path(@workout.id) %></h3>
  <% @exercises.each do |exercise| %>
    <table class= "all_exercises">
      <th colspan="2"><%= link_to " DO #{exercise.name.upcase}", new_exercise_exercise_history_path(exercise.id)%></th>
      <tr>
        <td>SETS</td>
        <td><%= exercise.sets %></td>
      </tr>
       <tr>
         <td>REPS</td>
         <td><%= exercise.reps %></td>
       </tr>
       <tr>
        <td>WEIGHT</td>
        <td><%= exercise.weight %></td>
      </tr>
      <tr>
        <td>TEMPO</td>
        <td><%= exercise.tempo %></td>
      </tr>
      <tr>
        <td>REST</td>
        <td><%= exercise.rest %></td>
      </tr>
    </table>
  <% end %>
</div>